language: r
r: 3.6.3

cache: packages
warnings_are_errors: false

r_packages:
  - covr
  - lintr

before_install:
  - cd comoOdeCpp

global:
  - R_BUILD_ARGS="--no-build-vignettes --no-manual"
  - R_CHECK_ARGS="--no-build-vignettes --no-manual"
  
r_build_args: --no-build-vignettes --no-manual
r_check_args: --no-build-vignettes --no-manual

after_script:
  - R CMD INSTALL $PKG_TARBALL
  - Rscript -e 'lintr::lint_package()'
  
after_success:
  - Rscript -e 'library(covr);codecov()'
  - Rscript -e 'covr::coveralls()'